---
title: "Untitled"
author: "Austin Pate"
date: "October 18, 2017"
output: pdf_document
---


```{r}
library(dplyr)
library(syuzhet)
library(readr)
library(stringr)
library(reshape2)
library(ggplot2)
library(igraph)
library(sna)
library(networkD3)
library(magrittr)
```

```{r}
setwd("C:/Users/Austin/Desktop/ww project/Analysis/Season 1")
all.ww <- read.csv("all.ww.ls.csv")

#Subsets seasons 1-7
for(i in 1:7){
  assign(paste0("season.",i), 
  subset(all.ww, season == i))
}

#Subsets season 1 episodese
for(i in 1:9){
   assign(paste0("s01e0",i), subset(season.1, episode.in.season == i))
}
for(i in 10:22){
   assign(paste0("s01e",i), subset(season.1, episode.in.season == i))
}

#Subsets season 2 episodes
for(i in 1:9){
   assign(paste0("s02e0",i), subset(season.2, episode.in.season == i))
}
for(i in 10:22){
   assign(paste0("s02e",i), subset(season.2, episode.in.season == i))
}

#Subsets season 3 episodes
for(i in 1:9){
   assign(paste0("s03e0",i), subset(season.3, episode.in.season == i))
}
for(i in 10:21){
   assign(paste0("s03e",i), subset(season.3, episode.in.season == i))
}

#Subsets season 4 episodes
for(i in 1:9){
   assign(paste0("s04e0",i), subset(season.4, episode.in.season == i))
}
for(i in 10:23){
   assign(paste0("s04e",i), subset(season.4, episode.in.season == i))
}

#Subsets season 5 episodes
for(i in 1:9){
   assign(paste0("s05e0",i), subset(season.5, episode.in.season == i))
}
for(i in 10:22){
   assign(paste0("s05e",i), subset(season.5, episode.in.season == i))
}

#Subsets season 6 episodes
for(i in 1:9){
   assign(paste0("s06e0",i), subset(season.6, episode.in.season == i))
}
for(i in 10:22){
   assign(paste0("s06e",i), subset(season.6, episode.in.season == i))
}

#Subsets season 6 episodes
for(i in 1:9){
   assign(paste0("s07e0",i), subset(season.7, episode.in.season == i))
}
for(i in 10:22){
   assign(paste0("s07e",i), subset(season.7, episode.in.season == i))
}

```


```{r}
#Calculates cross-tabs on characters and lines within a scene
by_speaker_scene_01 <- s01e01 %>%
    count(scene.in.episode, character)
by_speaker_scene_01

#Uses the saved cross-tabs to identify which characters overlap in a scene
speaker_scene_matrix_01 <- by_speaker_scene_01 %>%
    acast(character ~ scene.in.episode, fun.aggregate = length)
dim(speaker_scene_matrix_01)

#Creates dendogram based on the scene overlap
norm.01 <- speaker_scene_matrix_01 / rowSums(speaker_scene_matrix_01)
h.01 <- hclust(dist(norm.01, method = "manhattan"))
plot(h.01)

#Shows the ordering of characters (the closer they appear on the list, the more "similar" they are)
ordering.01 <- h.01$labels[h.01$order]
ordering.01

scenes_01 <- by_speaker_scene_01 %>%
    filter(n() > 1) %>%        # scenes with > 1 character
    ungroup() %>%
    mutate(scene = as.numeric(factor(scene.in.episode)),
           character = factor(character, levels = ordering.01))

ggplot(scenes_01, aes(scene, character)) +
    geom_point() +
    geom_path(aes(group = scene))

character.scene.overlap.01 <- speaker_scene_matrix_01 %*% t(speaker_scene_matrix_01)
heatmap(character.scene.overlap.01)

g_01 <- graph.adjacency(character.scene.overlap.01, weighted = TRUE, mode = "undirected", diag = FALSE)
plot(g_01, edge.width = E(g_01)$weight)

members <- communities(character.scene.overlap.01)

g_01_2 <-igraph_to_networkD3(g_01)
write.csv(a,"g_01.csv")
a<-get.edgelist(g_01)
simpleNetwork(as.data.frame(a))
forceNetwork(Links = g_01$links, Nodes = g_01$nodes, NodeID = 'name')
radialNetwork(List = as.list(a), fontSize = 10, opacity = 0.9)

wc_15<-cluster_walktrap(g_15)
members_15 <- membership(wc_15)
g_15_2<-igraph_to_networkD3(g_15, group = members_15)
forceNetwork(Links = g_15_2$links, Nodes = g_15_2$nodes, 
             Source = 'source', Target = 'target', 
             NodeID = 'name', Group = 'group',opacity = 1, fontSize = 14)

wc_01<-cluster_walktrap(g_01)
members_01 <- membership(wc_01)
g_01_2<-igraph_to_networkD3(g_01, group = members_01)
forceNetwork(Links = g_01_2$links, Nodes = g_01_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 0.8, fontSize = 14)
auth
g_01_2$nodes
pr$pr
pr$pr <-pr$pr*10
%>%
saveNetwork(file = 'Net1.html')

forcenet
dendroNetwork(h.02, nodeColour = "steel blue", zoom = TRUE)
dendroNetwork(h.02, nodeColour = "steel blue")
g_01_2$nodes
w<-data(MisLinks)
l<-data(MisNodes)
MisLinks
MisNodes

forceNetwork(Links = MisLinks, Nodes = MisNodes,
             Source = 'source', Target = 'target',
             NodeID = 'name', Group = 'group')
```

```{r}
wc_01<-cluster_walktrap(g_01)
members_01 <- membership(wc_01)
g_01_2<-igraph_to_networkD3(g_01, group = members_01)
forceNetwork(Links = g_01_2$links, Nodes = g_01_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)

wc_02<-cluster_walktrap(g_02)
members_02 <- membership(wc_02)
g_02_2<-igraph_to_networkD3(g_02, group = members_02)
forceNetwork(Links = g_02_2$links, Nodes = g_02_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)

wc_03<-cluster_walktrap(g_03)
members_03 <- membership(wc_03)
g_03_2<-igraph_to_networkD3(g_03, group = members_03)
forceNetwork(Links = g_03_2$links, Nodes = g_03_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)

wc_04<-cluster_walktrap(g_04)
members_04 <- membership(wc_04)
g_04_2<-igraph_to_networkD3(g_04, group = members_04)
forceNetwork(Links = g_04_2$links, Nodes = g_04_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)

wc_05<-cluster_walktrap(g_05)
members_05 <- membership(wc_05)
g_05_2<-igraph_to_networkD3(g_05, group = members_05)
forceNetwork(Links = g_05_2$links, Nodes = g_05_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)

wc_06<-cluster_walktrap(g_06)
members_06 <- membership(wc_06)
g_06_2<-igraph_to_networkD3(g_06, group = members_06)
forceNetwork(Links = g_06_2$links, Nodes = g_06_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)

wc_07<-cluster_walktrap(g_07)
members_07 <- membership(wc_07)
g_07_2<-igraph_to_networkD3(g_07, group = members_07)
forceNetwork(Links = g_06_2$links, Nodes = g_06_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)

wc_08<-cluster_walktrap(g_08)
members_08 <- membership(wc_08)
g_08_2<-igraph_to_networkD3(g_08, group = members_08)
forceNetwork(Links = g_08_2$links, Nodes = g_08_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)

wc_09<-cluster_walktrap(g_09)
members_09 <- membership(wc_09)
g_09_2<-igraph_to_networkD3(g_09, group = members_09)
forceNetwork(Links = g_09_2$links, Nodes = g_09_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)

wc_10<-cluster_walktrap(g_10)
members_10 <- membership(wc_10)
g_10_2<-igraph_to_networkD3(g_10, group = members_10)
forceNetwork(Links = g_10_2$links, Nodes = g_10_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)

wc_11<-cluster_walktrap(g_11)
members_11 <- membership(wc_11)
g_11_2<-igraph_to_networkD3(g_11, group = members_11)
forceNetwork(Links = g_11_2$links, Nodes = g_11_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)

wc_12<-cluster_walktrap(g_12)
members_12 <- membership(wc_12)
g_12_2<-igraph_to_networkD3(g_12, group = members_12)
forceNetwork(Links = g_12_2$links, Nodes = g_12_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)
            
wc_13<-cluster_walktrap(g_13)
members_13 <- membership(wc_13)
g_13_2<-igraph_to_networkD3(g_13, group = members_13)
forceNetwork(Links = g_13_2$links, Nodes = g_13_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)
            
wc_14<-cluster_walktrap(g_14)
members_14 <- membership(wc_14)
g_14_2<-igraph_to_networkD3(g_14, group = members_14)
forceNetwork(Links = g_14_2$links, Nodes = g_14_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)

wc_15<-cluster_walktrap(g_15)
members_15 <- membership(wc_15)
g_15_2<-igraph_to_networkD3(g_15, group = members_15)
forceNetwork(Links = g_15_2$links, Nodes = g_15_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)
            
wc_16<-cluster_walktrap(g_16)
members_16 <- membership(wc_16)
g_16_2<-igraph_to_networkD3(g_16, group = members_16)
forceNetwork(Links = g_16_2$links, Nodes = g_16_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)
            
wc_17<-cluster_walktrap(g_17)
members_17 <- membership(wc_17)
g_17_2<-igraph_to_networkD3(g_17, group = members_17)
forceNetwork(Links = g_17_2$links, Nodes = g_17_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)
            
wc_18<-cluster_walktrap(g_18)
members_18 <- membership(wc_18)
g_18_2<-igraph_to_networkD3(g_18, group = members_18)
forceNetwork(Links = g_18_2$links, Nodes = g_18_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)
            
wc_19<-cluster_walktrap(g_19)
members_19 <- membership(wc_19)
g_19_2<-igraph_to_networkD3(g_19, group = members_19)
forceNetwork(Links = g_19_2$links, Nodes = g_19_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)

wc_20<-cluster_walktrap(g_20)
members_20 <- membership(wc_20)
g_20_2<-igraph_to_networkD3(g_20, group = members_20)
forceNetwork(Links = g_20_2$links, Nodes = g_20_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)
            
wc_21<-cluster_walktrap(g_21)
members_21 <- membership(wc_21)
g_21_2<-igraph_to_networkD3(g_21, group = members_21)
forceNetwork(Links = g_21_2$links, Nodes = g_21_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)
            
wc_22<-cluster_walktrap(g_22)
members_22 <- membership(wc_22)
g_22_2<-igraph_to_networkD3(g_22, group = members_22)
forceNetwork(Links = g_22_2$links, Nodes = g_22_2$nodes,
            Source = "source", Target = "target",
            NodeID = "name",  Group = "group", opacity = 1, fontSize = 14)
```

